export default {
  NonExclusiveMusicTxt: `<p>YOU ACKNOWLEDGE AND AGREE THAT YOU HAVE READ THIS AGREEMENT AND HAVE BEEN ADVISED BY US OF THE SIGNIFICANT IMPORTANCE OF RETAINING AN INDEPENDENT ATTORNEY OF YOUR CHOICE TO REVIEW THIS AGREEMENT ON YOUR BEHALF. YOU ACKNOWLEDGE AND AGREE THAT YOU HAVE HAD THE UNRESTRICTED OPPORTUNITY TO BE REPRESENTED BY AN INDEPENDENT ATTORNEY. IN THE EVENT OF YOUR FAILURE TO OBTAIN AN INDEPENDENT ATTORNEY OR WAIVER THEREOF, YOU HEREBY WARRANT AND REPRESENT THAT YOU WILL NOT ATTEMPT TO USE SUCH FAILURE AND/OR WAIVER AS A BASIS TO AVOID ANY OBLIGATIONS UNDER THIS AGREEMENT, OR TO INVALIDATE THIS AGREEMENT OR TO RENDER THIS AGREEMENT OR ANY PART THEREOF UNENFORCEABLE.</p>
  <p>&nbsp;</p>
  <p>This non-exclusive copyright license agreement (the &ldquo;Agreement&rdquo;), created on and effective as of [DATE] (the &ldquo;Effective Date&rdquo;) is between [SELLER] (the &ldquo;Licensor&rdquo;) and [BUYER] (the &ldquo;Licensee&rdquo;).</p>
  <p>&nbsp;</p>
  <p>The Licensor hereby warrants that Licensor owns the copyright to the musical work to be licensed (the &ldquo;Music&rdquo;) and/or has the necessary permissions to license the Music. The Licensee wants to obtain, and the Licensor has agreed to grant, a license authorizing the use of the Music in the preparation of one or more Collective Works or Derivative Works for one or more of the purposes defined below.</p>
  <p>&nbsp;</p>
  <p>The parties therefore agree as follows:</p>
  <p>&nbsp;</p>
  <p>1. GRANT OF LICENSE.</p>
  <p>a. The Licensor hereby grants to Licensee a nonexclusive, nontransferable license to exercise the following rights in the Music, in all media (including electronic, video, audio, and any other technology now known or that may be developed in the future):</p>
  <p>i. to incorporate, include and/or use the Music in the preparation of one or more Collective Works. &ldquo;Collective Works&rdquo; means any work, including music or video compilations, in which the entire unmodified Music is assembled with other contributions, each constituting separate and independent works in themselves, into a collective whole;</p>
  <p>ii. to create and reproduce one or more Derivative Works. &ldquo;Derivative Works&rdquo; means any work based on the Music, or on the Music and other preexisting works, including a new piece of instrumental music created by the Licensee, a song made by recording written lyrics over the Music, and/or an audiovisual work created with the Music. Permission is granted to Licensee to modify the arrangement, length, tempo, or pitch of the Music in preparation of the Derivative Work for public release. A work constituting a Collective Work is not considered a Derivative Work under this agreement; and</p>
  <p>iii. to distribute copies of, display, perform publicly, or use in any advertising the Music, including as incorporated in Collective Works or Derivative Works.</p>
  <p>&nbsp;</p>
  <p>2. RESTRICTIONS.</p>
  <p>a. The license granted in section 1 above is subject to and limited by the following restrictions:</p>
  <p>i. Limited Use. The permissions granted to the Licensee under this agreement apply only to the uses and purposes stated and the Licensee may distribute, publicly perform, or use in any advertising the Music only under the terms of this agreement. The Licensee may not sublicense the Music or transfer this license, without the prior written consent of the Licensor. Any use that is inconsistent with the limited license provided in this agreement will be a violation of the Licensor's copyright and subject to copyright law. Should Licensee use the Music in a Derivative Work or Collective Work that creates a work of joint authorship with any third party, said third party must either also purchase a license from Licensor or agree to be bound to this agreement as a licensee in writing with the express permission of Licensor.</p>
  <p>ii. No Modification. The Licensee may not modify, copy, distribute, display, reproduce, publish, license, create derivative works from, sublicense, or transfer the Music obtained from the Licensor in any way not specifically granted in section 1 above without the prior written consent of the Licensor.</p>
  <p>iii. Right of Review. The Licensor may review any Collective Work or Derivative Work before publication and if the Music exceeds 50% of its total content the Licensor shall instead be entitled to receive a yyy% royalty and the work created by Licensee shall be considered a non-transformative work.</p>
  <p>iv. Limitations on Transfer. The license hereby granted is not transferable, is not exclusive, and applies only to the Music being licensed in this transaction.</p>
  <p>v. No Other Work. The Licensor grants no other right or license to the Licensee, either express or implied, with respect to any other copyright or other intellectual property right owned, possessed, or licensed by the Licensor.</p>
  <p>&nbsp;</p>
  <p>3. NO ASSIGNMENT OR TRANSFER.</p>
  <p>a. The rights granted to the Licensee by this agreement are license rights only and nothing in this agreement constitutes an assignment or exclusive license of the Licensor's rights in the Music. The Licensor retains ownership of the copyright in the Music, and all rights not expressly granted in this agreement.</p>
  <p>&nbsp;</p>
  <p>4. CREDIT AND SAMPLES.</p>
  <p>a. Credit. Acknowledgement of the original creator of the Music is automatically conferred through the normal processes of the Craft Music mobile app when</p>
  <p>making a derivative work. If Licensee wishes to use the work outside of the Craft Music mobile app, Licensee should ask Licensor how Licensor should be credited, if at all.</p>
  <p>b. Copy of Work. On the Licensor&rsquo;s request, the Licensee shall provide the Licensor with a copy of each Collective Work and Derivative Work incorporating the Music to allow the Licensor to confirm compliance with the grant of permission given under this agreement. Derivative works are automatically tracked through the normal processes of the Craft Music app; if you upload the work through another process, or use the work outside of the app, you must provide Licensor with a copy of work upon request.</p>
  <p>c. Copies of Advertisements. The Licensee will submit to the Licensor two copies of any advertising material that will accompany distribution of the Music, or any Collective Work or Derivative Work.</p>
  <p>d. Copy of Critical Work. If the Music will be reproduced in a Collective Work or Derivative Work as a subject of criticism, a copy of the text addressing the Music must accompany this agreement.</p>
  <p>&nbsp;</p>
  <p>5. FEES.</p>
  <p>a. License Issue Fee. On the effective date of this agreement (as described in section 21 below), the Licensee shall pay to the Licensor a nonrefundable fee which is currently listed for the work on the Craft Music app (the &ldquo;License Issue Fee&rdquo;). The License Issue Fee is not an advance toward royalties that may become due during any calendar quarter and the Licensee shall not deduct the amount of the License Issue Fee from any royalties that may become due from the sale of a Collective Work or Derivative Work.</p>
  <p>b. Advertising Fee. The Licensee shall pay to the Licensor $zzz for any non-transformative use of any Collective Work within an advertisement. This Advertising Fee allows the Licensee use of said Collective Work www times. Once Licensee has exceeded the permitted number of uses, a new Advertising Fee must be paid for any further non-transformative use of any Collective Work in an advertisement.</p>
  <p>c. Royalties. The Licensee shall pay to the Licensor, in addition to the License Issue Fee, a continuing royalty of xxx% of Gross Sales of the price sold to the end users of any Collective Work, and/or any Derivative Work incorporating any part of the Music sold by the Licensee or any of its subsidiaries, divisions, agents, owners, or affiliates, even if sold by third party distributors. If the Collective Work or Derivative Work is performed, licensed for streaming, or otherwise used in conjunction with advertising revenue, or revenue received from patronage, Licensor shall instead receive xxx% of the gross revenue received by any person so exploiting the Collective work or the Derivative Work (&ldquo;Gross Revenue&rdquo;). Any non-transformative use of the Music shall have a yyy% royalty of the amount paid by the end user or any other amount generated by the non-transformative use of the Music.</p>
  <p>d. Licensee hereby warrants that it will not create a Derivative Work or Collective Work where the total royalties owed would be more than 100% of the Gross Sales</p>
  <p>or Gross Revenue generated or otherwise encumber such sales in any way that would make it impossible for the royalty to be paid as contained herein.</p>
  <p>e. If the Gross Sales plus Gross Revenue are equal to or greater than $80,000, Licensee shall also pay to Craft Music a transaction fee royalty of 5% of Gross Sales and Gross Revenue. &ldquo;Gross Sales&rdquo; means the Licensee's billing price to customers or distributors, including the royalty amount less:</p>
  <p>i. customary trade discounts actually given;</p>
  <p>ii. returns; and</p>
  <p>iii. transportation charges on returns.</p>
  <p>&ldquo;Gross Revenue&rdquo; means any monetary renumeration received by Licensee arising from or related to the Derivative Work or Collective Work other than a sale of said work.</p>
  <p>If the Licensee sells the Collective Work or any Derivative Work to any party affiliated with the Licensee, or in any way related to or under common control with the Licensee, at a price less than the regular price charged to other parties, the royalties will be computed on the basis of the regular price charged to other parties. No deduction from the royalties owed will be allowed for uncollectible accounts, or for taxes, fees, assessments, advertising, or other expenses of any kind that maybe incurred or paid by the Licensee, except as specifically enumerated in the definition of Gross Sales. The Licensee shall report and pay royalties quarterly. The royalty report deadline is 30 days after the end of each calendar quarter. For clarity, the Licensee may not merely sell the Music in its original form.</p>
  <p>f. If Licensee registers the Derivative Work or Collective Work with a Performing Rights Organization (PRO), Licensee shall register the work such that Licensor is entitled to xxx% of the proceeds of the exploitation of the work via the PRO.</p>
  <p>&nbsp;</p>
  <p>6. DELIVERY OF MUSIC.</p>
  <p>a. The Licensor will provide a high-quality electronic version of the Music from which the Licensee can use the Music solely for the purposes described in this agreement. Delivery will occur via the Craft Music app, as soon as payment is complete.</p>
  <p>&nbsp;</p>
  <p>7. OWNERSHIP AND USE OF MUSIC.</p>
  <p>a. Ownership of Music. The Licensee acknowledges that the Licensor is the owner of the Music and of all associated federal registrations and pending registrations, and the Licensee shall do nothing inconsistent with that ownership. The Licensee may not claim ownership rights to the Music, or any derivative, compilation, sequel or series, or related work owned or used by the Licensor. Nothing in this agreement gives the Licensee any interest in the Music other than the right to use them in accordance with this agreement.</p>
  <p>b. Validity of Registrations. The Licensee admits the validity of all copyrights for the Music and all associated registrations and acknowledges that all rights that might be acquired to Music by the Licensee because of its use of the Music shall inure to the sole benefit of the Licensor. The previous notwithstanding this subsection does not entitle the Licensor to any of the revenues from the</p>
  <p>Licensee&rsquo;s permitted uses under this agreement, except for the fees described in section 5 above.</p>
  <p>c. Limitation on Licensee&rsquo;s Actions. The Licensee may not do anything inconsistent with the Licensor&rsquo;s ownership of the Music, claim adversely to the Licensor, or assist any third party in attempting to claim adversely to the Licensor, with regards to that ownership. The Licensee may not challenge the Licensor's title to the Music, oppose any registration or re-registrations of the Music, or challenge the validity of this agreement or the grants provided under it. The Licensee may only not register the Music or any part thereof except in so far as they are registered by Licensee as a Collective Works or Derivative Works created from the Music which explicitly states that no claim is made to the Music except as the Music is used in conjunction with the Collective Works or Derivative Works being registered as Collective Works or Derivative Works. The Licensee may not re-sell or exploit the Music in its original form, or in a form with merely deminimus changes or deminimus additions. Licensee may only sell or exploit Collective Works or Derivative Works created from the Music that are transformative in nature. Any sale of the Music in its original form constitutes a material breach of this Agreement and the Licensee shall be liable to Licensor for any resulting damages incurred including and not limited to exemplary damages, as if the Music has been registered as a copyright, regardless of whether the Music has actually been so registered.</p>
  <p>&nbsp;</p>
  <p>8. REPRESENTATIONS.</p>
  <p>The Licensor hereby represents that:</p>
  <p>a. the Licensor is either the sole owner of all interest in the Music or otherwise has such licenses and permissions as necessary to allow this transaction upon the terms contained herein;</p>
  <p>b. the Music does not infringe on the intellectual property rights of any third party, is not in the public domain, and does not contain anything that is illegal or legally defined as &ldquo;obscene&rdquo; by U.S. law;</p>
  <p>c. the Licensor has not transferred, exclusively licensed, or encumbered the Music or agreed to do so;</p>
  <p>d. the Licensor is not aware of any violation, infringement, or misappropriation of any third party's rights or any claims of rights (including existing intellectual property rights, rights of privacy, or any other rights) by the Music;</p>
  <p>e. the Licensor is not aware of any third-party consents, assignments, or licenses that are necessary to meet its obligations under this agreement; and</p>
  <p>f. the Licensor was not acting within the scope of employment of a third party when conceiving, creating, or otherwise performing any activity with respect to the Music purportedly licensed in section 1.</p>
  <p>The Licensee hereby warrants that it will take no action or series of actions or inactions that would effect a circumvention of this Agreement or Licensor&rsquo;s right to renumeration as contemplated from this Agreement whether or not such actions are or are not explicitly or implicitly restricted by this Agreement. It is the express intent of both Parties that the Licensor receive xxx% of any gross proceeds generated by, arising from, or related to the Music.</p>
  <p>There is no intention by the Parties to create a joint work, and there is no intention by the Licensor to grant any rights in and/or to any other derivative works that may have been created by other third-party licensees.</p>
  <p>&nbsp;</p>
  <p>9. DOCUMENTATION.</p>
  <p>a. Recordation of Agreement. The Licensor will, as soon as is reasonably possible following a request from the Licensee, provide the Licensee with a complete copy of all documentation (in any format) relating to the Music for the Licensee&rsquo;s own use, to meet record-keeping requirements of the Licensee, or to allow the Licensee to exercise its rights granted under this agreement. The Licensor will also, on request:</p>
  <p>i. execute any additional papers, including any separate licenses of the Music, reasonably necessary to record the license in the United States and throughout the world; and</p>
  <p>ii. generally do all other lawful acts reasonable and necessary to record the agreement in the United States and throughout the world.</p>
  <p>b. Licensee Assistance in Maintaining Work. The Licensee shall on request give to the Licensor or its authorized representatives any information as to its use of the Music, any Collective Work, or any Derivative Work that the Licensor may reasonably require and will render any (nonmonetary) assistance reasonably required by the Licensor in maintaining the Music or any registrations of the Music.</p>
  <p>&nbsp;</p>
  <p>10. INDEMNIFICATION.</p>
  <p>If the Music infringes on any United States copyright of a third party not affiliated with the Licensee, the Licensor shall indemnify the Licensee against that claim if all of the following are true:</p>
  <p>a. the Licensee promptly notifies the Licensor of that claim;</p>
  <p>b. the Licensor controls the defense and settlement of that claim;</p>
  <p>c. the Licensee fully cooperates with the Licensor in connection with its defense and settlement of that claim;</p>
  <p>d. the Licensee stops all sales, distribution, and public use of or relating to the infringing Music, including as necessary any Collective Works or Derivative Works, if requested by the Licensor.</p>
  <p>If the Licensee is enjoined from further use of any infringing Music or if the Licensee stops using any of the Music (including as necessary any Collective Works or Derivative Works) because of the Licensor's request (as described in (d) above), the Licensor shall, at its own expense and option:</p>
  <p>a. obtain the right for the Licensee to continue to use the infringing Music;</p>
  <p>b. modify the infringing Music to eliminate that infringement (if practicable); or</p>
  <p>c. refund the amount paid under this agreement for the infringing Music to the Licensee, on such terms as the parties may agree.</p>
  <p>d. Reimburse Licensee for any costs or damages directly attributable to the Music infringing third party intellectual property that is assessed by a court of competent jurisdiction in the United State of America.</p>
  <p>The Licensor shall have no other obligations or liability if infringement occurs and shall have no other obligation of indemnification relating to infringement. The Licensor shall not be liable for any costs or expenses incurred without its prior written authorization and shall have no obligation of indemnification or any liability if the infringement is based on:</p>
  <p>a. any changed form of the Music not made by the Licensor; or</p>
  <p>b. the laws of any country other than the United States of America or its states.</p>
  <p>&nbsp;</p>
  <p>11. TERMINATION.</p>
  <p>a. Term: The Term of this Agreement as it applies to Collective Works or Derivative works Published by the Licensee shall last so long as Licensee has fully complied with the terms of this Agreement and the Music has not entered the public domain. The Licensee shall only have the ability to create new Collective Works or Derivative Works based on the Music during a 2-year period ending on the 2-year anniversary of the Effective Date.</p>
  <p>b. The agreement will terminate immediately, without notice, if:</p>
  <p>i. the Music enters the public domain;</p>
  <p>ii. before publication, the Licensee has not complied with this agreement;</p>
  <p>iii. the Licensee attempts to transfer any of the rights granted to the Licensee in connection with this agreement without obtaining the Licensor's prior written consent;</p>
  <p>iv. the Licensee uses the Music in a manner not expressly permitted by this agreement;</p>
  <p>v. no Collective Work, Derivative Work, or reproduction of Music is published within one year of the effective date of this agreement, unless extended by written permission of the Licensor;</p>
  <p>vi. the copyright and acknowledgment notices are not printed as specified in section 4; or</p>
  <p>vii. Licensor earns no royalty on the Music, pursuant to this agreement for a period of at least 6 months following the 1-year anniversary of this agreement.</p>
  <p>c. The Agreement will terminate with 15 days prior notice being sent to the Licensee, in the event that any payment due under this agreement is not paid when due. The licensee shall have the right to cure said breach within the 10-day notice period. During any good faith disagreement on amounts due, the Licensor may request that a certified accountant review the books and records of Licensee to ensure compliance with this Agreement. If such an accountant shall determine that the books of Licensee were not sufficiently kept for said accountant to make an accurate determination, that licensee was unhelpful in the conduct of the audit, or that any amount remains owed and outstanding from Licensee to Licensor, Licensor shall have an additional 10 days to cure, or this Agreement shall be terminated.</p>
  <p>d. Effect of Termination. All rights granted by this agreement, including the Licensee's right to use the Music, shall end on termination of this agreement. On termination of this agreement, the Licensee shall promptly discontinue all use of Music, any Collective Work, or any Derivative Work, and refrain from further</p>
  <p>reproduction, publishing, performance or distributing of the Collective Work or Derivative Work. However, the Licensee may fill existing orders and sell off existing copies of Collective Works or Derivative Works then in stock if the sell-off period is no more than three months from the date of termination. Any sales of Collective Works or Derivative Works during this wind down period will constitute Gross Sales and the above royalties must be paid on said sales. If the Licensee is in arrears on payments owed to Licensor, the entire proceeds of said sales shall be paid to Licensor until all amounts owed are fully satisfied. The Licensor shall have the right to verify the existence and validity of the existing orders and existing copies of the Collective Work or Derivative Work then in stock on reasonable notice to the Licensee.</p>
  <p>e. Licensee agrees that a breach or threatened breach of this Agreement by Licensee give rise to irreparable injury to Licensor, which may not be adequately compensated by damages. Accordingly, in the event of a breach or threatened breach by the Licensee of the provisions of this Agreement, Licensor may seek and shall be entitled to a temporary restraining order and a preliminary injunction restraining the Licensee from violating the provisions of this Agreement. Nothing herein shall prohibit Licensor from pursuing any other available legal or equitable remedy from such breach or threatened breach, including but not limited to the recovery of damages from the Licensee. The Licensee shall be responsible for all costs, expenses or damages that Licensor incurs as a result of any violation by the Licensee of any provision of this Agreement. Licensee&rsquo; obligation shall include court costs, litigation expenses, and reasonable attorneys' fees.</p>
  <p>&nbsp;</p>
  <p>12. GOVERNING LAW.</p>
  <p>a. Choice of Law. The laws of the jurisdiction in which the Licensor resides at the time of sale govern this agreement (without giving effect to its conflicts of law principles but giving full effect to any and all applicable international treaties made between Licensor and Licensee&rsquo;s countries of residence).</p>
  <p>b. Choice of Forum. Both parties consent to the personal jurisdiction of the state and federal courts in the Licensor&rsquo;s county and state or foreign equivalent jurisdiction.</p>
  <p>c. The parties hereby agree that the decision made by such courts shall be considered arbitral awards for the purpose of foreign enforcement of said awards as if said adjudicator was appointed as the arbitrator, and the laws and government of said jurisdiction the as the arbitral institution. If any country refuses to enforce such a judgement as an arbitral award, the parties do hereby authorize the judgment to be sent to an Arbitrator in Atlanta, Georgia under the auspices of the American Arbitration Association, said arbitrator having solely the power and authority to produce an award identical to the judgement created by the adjudicating court in the Licensor&rsquo;s place of residence at the time of sale, the costs of which shall be borne by the losing party of the original action.</p>
  <p>&nbsp;</p>
  <p>13. AMENDMENTS.</p>
  <p>No amendment to this agreement will be effective unless it is in writing and signed by a party or its authorized representative.</p>
  <p>&nbsp;</p>
  <p>14. ASSIGNMENT AND DELEGATION.</p>
  <p>a. No Assignment. Neither party may assign any of its rights under this agreement, except with the prior written consent of the other party. All voluntary assignments of rights are limited by this subsection. The previous notwithstanding, the Licensor may assign its right to receive payments to a third-party, however the Licensee may continue to make payments to the either the third party or Licensor and it is the Licensor&rsquo;s sole responsibility to ensure that the assignee receives payments sent to Licensor.</p>
  <p>b. No Delegation. Neither party may delegate any performance under this agreement, except with the prior written consent of the other party.</p>
  <p>c. Enforceability of an Assignment or Delegation. If a purported assignment or purported delegation is made in violation of this section, it is void.</p>
  <p>&nbsp;</p>
  <p>15. COUNTERPARTS; ELECTRONIC SIGNATURES.</p>
  <p>a. Counterparts. The parties may execute this agreement in any number of counterparts, each of which is an original but all of which constitute one and the same instrument.</p>
  <p>b. Electronic Signatures. This agreement, agreements ancillary to this agreement, and related documents entered into in connection with this agreement are signed when a party's signature is delivered by facsimile, email, or other electronic medium, including clicking any button that constitute an offer or acceptance of the offer on the Craft Music App or Website. These signatures must be treated in all respects as having the same force and effect as original signatures. If any governing authority requires handwritten signatures to effectuate the intent of this Agreement the Parties agree to take such actions as are necessary to rectify any such requirements and to take such other actions as necessary to put the other Party in the position that they would be in had the execution of this agreement complied with local rules of contractual viability from the Effective Date.</p>
  <p>&nbsp;</p>
  <p>16. SEVERABILITY.</p>
  <p>If any one or more of the provisions contained in this agreement is, for any reason, held to be invalid, illegal, or unenforceable in any respect, that invalidity, illegality, or unenforceability will not affect any other provisions of this agreement, but this agreement will be construed as if those invalid, illegal, or unenforceable provisions had never been contained in it, unless the deletion of those provisions would result in such a material change so as to cause completion of the transactions contemplated by this agreement to be unreasonable.</p>
  <p>&nbsp;</p>
  <p>17. NOTICES.</p>
  <p>a. Writing; Permitted Delivery Methods. Each party giving or making any notice, request, demand, or other communication required or permitted by this agreement shall give that notice in writing and use one of the following types of delivery, each of which is a writing for purposes of this agreement: personal delivery, mail (registered or certified mail, postage prepaid, return-receipt requested), nationally recognized overnight courier (fees prepaid), facsimile, direct message, email, or other written electronic communication.</p>
  <p>b. Addresses. If submitting notice by mail or courier, a party shall address notices under this section to another party at the address provided by the other party.</p>
  <p>c. Effectiveness. A notice is effective only if the party giving notice complies with subsections (a) and (b) and if the recipient receives the notice, whether it is opened or unopened.</p>
  <p>&nbsp;</p>
  <p>18. WAIVER.</p>
  <p>No waiver of a breach, failure of any condition, or any right or remedy contained in or granted by the provisions of this agreement will be effective unless it is in writing and signed by the party waiving the breach, failure, right, or remedy. No waiver of any breach, failure, right, or remedy will be deemed a waiver of any other breach, failure, right, or remedy, whether or not similar, and no waiver will constitute a continuing waiver, unless the writing so specifies.</p>
  <p>&nbsp;</p>
  <p>19. ENTIRE AGREEMENT.</p>
  <p>This agreement constitutes the final agreement of the parties. It is the complete and exclusive expression of the parties&rsquo; agreement about the subject matter of this agreement. All prior and contemporaneous communications, negotiations, and agreements between the parties relating to the subject matter of this agreement are expressly merged into and superseded by this agreement. The provisions of this agreement may not be explained, supplemented, or qualified by evidence of trade usage or a prior course of dealings. Neither party was induced to enter this agreement by, and neither party is relying on, any statement, representation, warranty, or agreement of the other party except those set forth expressly in this agreement. Except as set forth expressly in this agreement, there are no conditions precedent to this agreement&rsquo;s effectiveness.</p>
  <p>&nbsp;</p>
  <p>20. HEADINGS.</p>
  <p>The descriptive headings of the sections and subsections of this agreement are for convenience only, and do not affect this agreement's construction or interpretation.</p>
  <p>&nbsp;</p>
  <p>21. EFFECTIVENESS.</p>
  <p>This agreement will become effective once purchase and sale is made between the parties via the Craft Music mobile app. The date of purchase will be deemed the date of this agreement.</p>
  <p>&nbsp;</p>
  <p>22. NECESSARY ACTS; FURTHER ASSURANCES.</p>
  <p>Each party shall use all reasonable efforts to take, or cause to be taken, all actions necessary or desirable to consummate and make effective the transactions this agreement contemplates or to evidence or carry out the intent and purposes of this agreement.</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>THE LICENSEE IS EXPRESSLY PROHIBITED FROM REGISTERING THE MUSIC AND/OR COLLECTIVE WORK AND/OR DERIVATIVE WORK WITH ANY CONTENT IDENTIFICATION SYSTEM, SERVICE PROVIDER, MUSIC DISTRIBUTOR, RECORD LABEL OR DIGITAL AGGREGATOR (for example, TuneCore or CDBaby, and any other provider of user-generated content identification</p>
  <p>ntification</p>
  <p>t takedown notice from a third party who also received a non-exclusive license to use the Music. If you do not adhere to this policy, you are in violation of the terms of this License and your license to use the Music may be revoked without notice or compensation to you.</p>`,
};
